//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestPersoMail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taches
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string description { get; set; }
        public string fichiers { get; set; }
        public short importance { get; set; }
        public System.DateTime date_saisie { get; set; }
        public Nullable<int> utilisateur { get; set; }
        public bool Termine { get; set; }
        public Nullable<System.DateTime> date_normale { get; set; }
        public Nullable<System.DateTime> date_prioritaire { get; set; }
        public Nullable<System.DateTime> date_urgente { get; set; }
        public Nullable<System.DateTime> date_faible { get; set; }
    
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
